/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.cishiv.dominoes;

import org.junit.Test;
import static org.junit.Assert.*;

public class DominoesTest {
    @Test public void testAppHasAGreeting() {
        Dominoes classUnderTest = new Dominoes();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
